name: 'snies_challenge'
version: '1.0.0'
config-version: 2

profile: 'snies'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  snies_challenge:
    silver:
      +schema: silver
      +materialized: view
    gold:
      +schema: gold
      +materialized: table
