snies:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: postgres
      port: 5432
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      dbname: snies
      schema: public # Default schema, dbt project config overrides this for custom schemas
